#ifndef CBEAR_BERLIOS_DE_PP_WIDEN_HPP_INCLUDED
#define CBEAR_BERLIOS_DE_PP_WIDEN_HPP_INCLUDED

#define CBEAR_BERLIOS_DE_PP_WIDEN_I(X) L ## X
#define CBEAR_BERLIOS_DE_PP_WIDEN(X) CBEAR_BERLIOS_DE_PP_WIDEN_I(X)

#endif
