#ifndef CBEAR_BERLIOS_DE_PP_CAT_HPP_INCLUDED
#define CBEAR_BERLIOS_DE_PP_CAT_HPP_INCLUDED

#include <boost/preprocessor/cat.hpp>

#define CBEAR_BERLIOS_DE_PP_CAT3(A0, A1, A2) \
	BOOST_PP_CAT(BOOST_PP_CAT(A0, A1), A2)

#define CBEAR_BERLIOS_DE_PP_CAT4(A0, A1, A2, A3) \
	CBEAR_BERLIOS_DE_PP_CAT3(BOOST_PP_CAT(A0, A1), A2, A3)

#define CBEAR_BERLIOS_DE_PP_CAT5(A0, A1, A2, A3, A4) \
	CBEAR_BERLIOS_DE_PP_CAT4(BOOST_PP_CAT(A0, A1), A2, A3, A4)

#define CBEAR_BERLIOS_DE_PP_CAT6(A0, A1, A2, A3, A4, A5) \
	CBEAR_BERLIOS_DE_PP_CAT5(BOOST_PP_CAT(A0, A1), A2, A3, A4, A5)

#endif
